package ikame.docxreader.ui;

import org.openqa.selenium.By;

public class PageUI_DocxReader {
	public static final By TEXT_DOCX_READER = By.id("com.happydev.wordoffice:id/layoutAppTitle");
	public static final By ICON_AVATAR = By.id("com.happydev.wordoffice:id/tv_random_text_drawer");
	public static final By BUTTON_PREMIUM = By.id("com.happydev.wordoffice:id/btnPremium");
	public static final By BUTTON_SEARCH = By.id("com.happydev.wordoffice:id/btnSearch");
	public static final By BUTTON_SORT = By.id("com.happydev.wordoffice:id/btnSort");
	public static final By IMAGE_FOLDER = By.xpath("//android.widget.ScrollView[@resource-id='com.happydev.wordoffice:id/layoutPermission']//android.widget.ImageView");
	public static final By TEXT_TO_READ_AND_EDITDOCUMENTS = By.xpath("//android.widget.TextView[contains(@text,'access all your file')]");
	public static final By BUTTON_REQUESTPER_MISSION = By.id("com.happydev.wordoffice:id/tvGrantPms");
	public static final By TEXT_HOME = By.id("com.happydev.wordoffice:id/tv_document");
	public static final By ICON_HOME = By.id("com.happydev.wordoffice:id/iv_document");
	public static final By TEXT_RECENT = By.id("com.happydev.wordoffice:id/tv_recent");
	public static final By ICON_RECENT = By.id("com.happydev.wordoffice:id/iv_recent");
	public static final By TEXT_STORAGE = By.id("com.happydev.wordoffice:id/tv_storage");
	public static final By ICON_STORAGE = By.id("com.happydev.wordoffice:id/iv_storage");
	public static final By TEXT_TOOL = By.id("com.happydev.wordoffice:id/tv_tool");
	public static final By ICON_TOOL = By.id("com.happydev.wordoffice:id/iv_tool");
	public static final By ICON_CREATE = By.id("com.happydev.wordoffice:id/lottie_create");
	public static final By TEXT_ALL_FILES_ACCESS = By.xpath("//android.widget.FrameLayout[@content-desc='All files access']");
	public static final By ICON_DOCX_READER = By.id("com.android.settings:id/entity_header_icon");
	public static final By TEXT_DOCX_READER_IN_FILE_ACCESS = By.id("com.android.settings:id/entity_header_title");
	public static final By TEXT_SUMMARY = By.id("com.android.settings:id/entity_header_summary");
	public static final By TEXT_ALLOW_ACCESS = By.xpath("//android.widget.TextView[@text='Allow access to manage all files']");
	public static final By BUTTON_SWITCH_OFF = By.xpath("//android.widget.Switch[@resource-id='android:id/switch_widget' and @index='0']");
	public static final By TAB_ALL = By.xpath("//android.widget.TextView[@text='ALL']");
	public static final By LABEL_ADVERTISEMENT = By.id("com.happydev.wordoffice:id/customNativeInList_tvAdTxt");
	public static final By BUTTON_NAVIGATE = By.xpath("//android.widget.ImageButton[@content-desc='Navigate up']");
	public static final By BUTTON_CLOSE = By.id("com.happydev.wordoffice:id/btnClose");
	public static final By TEXT_UNLOCK_ALL_PREMIUM_BENEFITS = By.xpath("//android.widget.TextView[@text='Unlock all Premium benefits']");
	public static final By TEXTBOX_SEARCH = By.id("com.happydev.wordoffice:id/textSearch");
	public static final By IMG_SEARCH = By.xpath("//android.widget.LinearLayout[@resource-id='com.happydev.wordoffice:id/ln_tip_search']/android.widget.ImageView");
	public static final By BUTTON_IV_BACK = By.id("com.happydev.wordoffice:id/iv_back");
	public static final By ICON_TAKE = By.id("com.happydev.wordoffice:id/img_take");
	public static final By TEXT_MULTIPLE = By.id("com.happydev.wordoffice:id/img_take");
	public static final By TEXT_SINGLE = By.xpath("//android.widget.LinearLayout[@content-desc='Single']");
	public static final By BUTTON_HOME = By.id("com.happydev.wordoffice:id/ivHome");
	public static final By TEXT_PDF_FILE = By.xpath("//android.widget.TextView[@text='PDF File']");
	public static final By TEXT_CREATE = By.xpath("//android.widget.TextView[@text='Create']");
	public static final By TAB_DOCX = By.id("com.happydev.wordoffice:id/ln_doc");
	public static final By TAB_XLSX = By.id("com.happydev.wordoffice:id/ln_xls");
	public static final By TAB_PPTX = By.id("com.happydev.wordoffice:id/ln_ppt");
	public static final By TEXT_PDF_TOOLS = By.xpath("//android.widget.TextView[@text='PDF Tools']");
	public static final By TAB_MAY_YOU_LIKE = By.xpath("//android.widget.TextView[@text='May you like']");
	public static final By TAB_IMG_TO_PDF = By.id("com.happydev.wordoffice:id/ln_pic_to_pdf");
	public static final By TAB_SCAN_FILE = By.id("com.happydev.wordoffice:id/ln_scan_file");
	public static final By TAB_MERGE_PDF = By.id("com.happydev.wordoffice:id/ln_merge_to_pdf");
	public static final By TAB_SET_PASSWORD = By.id("com.happydev.wordoffice:id/ln_set_password");
	public static final By TAB_SPLIT_PDF = By.id("com.happydev.wordoffice:id/ln_split_pdf");
	public static final By TAB_CONVERT_TO_PDF = By.id("com.happydev.wordoffice:id/ln_file_to_pdf");
	public static final By TAB_SCANNER = By.id("com.happydev.wordoffice:id/ln_scan");
	public static final By TAB_TEXT_RECOGNIZE = By.id("com.happydev.wordoffice:id/ln_ocr_file");
	public static final By TAB_PRINT = By.id("com.happydev.wordoffice:id/ln_print");
	public static final By TAB_FILE_TRANSFER = By.id("com.happydev.wordoffice:id/ln_transfer");
	public static final By TAB_RECYCLE_BIN = By.id("com.happydev.wordoffice:id/ln_trash");
	public static final By TITLE_RECYCLE_BIN = By.id("com.happydev.wordoffice:id/textTilte");
	public static final By IMG_EMPTY_FILE = By.xpath("//android.widget.LinearLayout[@resource-id='com.happydev.wordoffice:id/layoutEmpty']/android.widget.ImageView");
	public static final By TEXT_NO_FILE_FOUND = By.xpath("//android.widget.TextView[@text='No file found']");
	public static final By IMG_PREMIUM = By.xpath("//android.widget.ImageView[@resource-id='com.happydev.wordoffice:id/iv_close_premium']//preceding-sibling::android.widget.ImageView");
	public static final By LIST_NAME_FILE = By.xpath("//android.widget.TextView[@resource-id='com.happydev.wordoffice:id/tv_doc_name']");
	public static final By LIST_CREATE_DATE_FILE = By.xpath("//android.widget.TextView[@resource-id='com.happydev.wordoffice:id/tv_doc_created_date']");
	public static final By LIST_SIZE_FILE = By.xpath("//android.widget.TextView[@resource-id='com.happydev.wordoffice:id/tv_doc_size']");
	public static final By LIST_ICON_FAVOURITE = By.xpath("//android.widget.ImageView[@resource-id='com.happydev.wordoffice:id/iv_favourite']");
	public static final By LIST_ICON_OPTION = By.xpath("//android.widget.ImageView[@resource-id='com.happydev.wordoffice:id/iv_option']");
	public static final By ICON_OPTION1 = By.xpath("(//android.widget.ImageView[@resource-id='com.happydev.wordoffice:id/iv_option'])[1]");
	public static final By TEXT_NAME_FILE = By.id("com.happydev.wordoffice:id/tv_doc_name");
	public static final By TEXT_CREATED_DATE = By.id("com.happydev.wordoffice:id/tv_doc_created_date");
	public static final By TEXT_SIZE_FILE = By.id("com.happydev.wordoffice:id/tv_doc_size");
	public static final By TAB_FAVOURITE = By.id("com.happydev.wordoffice:id/lnInfoFav");
	public static final By TEXT_UNFAVOURITE = By.xpath("//android.widget.TextView[@text='Unfavored']");
	public static final By TEXT_FAVOURITE = By.xpath("//android.widget.TextView[@text='Favourite']");	
	public static final By TAB_CREATE_SHORTCUT = By.id("com.happydev.wordoffice:id/lnInfoShortcut");
	public static final By TEXT_QUICKSTEP = By.id("com.google.android.apps.nexuslauncher:id/widget_appName");
	public static final By BUTTON_ADD_TO_HOME_SCREEN = By.xpath("//*[@text='Add to Home screen']");
	public static final By BUTTON_CANCEL= By.xpath("//android.widget.Button[@text='Cancel']");
	public static final By TAB_CONVERT_PDF= By.id("com.happydev.wordoffice:id/lnInfoConvertToPDF");
	public static final By TITLE_CONVERT_PDF = By.id("com.happydev.wordoffice:id/btnToolbarSlide");
	public static final By TITLE_CONVERT_PDF_TO_WORD = By.id("com.happydev.wordoffice:id/tvToolbarName");
	public static final By BUTTON_CONVERT_TO_PDF = By.id("com.happydev.wordoffice:id/btnConvert");
	public static final By BTN_TOOLBAR_BACK = By.id("com.happydev.wordoffice:id/btnToolbarBack");
	public static final By TAB_INFO_FILE = By.id("com.happydev.wordoffice:id/lnInfoInfo");
	public static final By TEXT_NAME = By.xpath("//android.widget.TextView[@text='Name:']");
	public static final By TEXT_PATH = By.xpath("//android.widget.TextView[@text='Path:']");
	public static final By TAB_SHARE_FILE = By.id("com.happydev.wordoffice:id/lnInfoShare");
	public static final By TITLE_SHARE = By.xpath("//android.widget.TextView[@text='Share']");
	public static final By IMG_HOME = By.id("com.happydev.wordoffice:id/iv_home");
	public static final By TAB_DELETE = By.id("com.happydev.wordoffice:id/lnInfoDelete");
	public static final By TEXT_REMOVE_THIS_ITEM = By.id("com.happydev.wordoffice:id/tv_delete_content");
	public static final By BTN_REMOVE = By.id("com.happydev.wordoffice:id/tv_confirm_delete");
	public static final By BTN_CANCEL = By.id("com.happydev.wordoffice:id/tv_cancel_delete");
	public static final By TAB_PDF = By.xpath("//android.widget.TextView[@text='PDF']");
	public static final By TAB_WORD = By.xpath("//android.widget.TextView[@text='WORD']");
	public static final By TAB_EXCEL = By.xpath("//android.widget.TextView[@text='EXCEL']");
	public static final By TAB_SLIDES = By.xpath("//android.widget.TextView[@text='SLIDES']");
	public static final By TAB_TEXT = By.xpath("//android.widget.TextView[@text='TEXT']");
	public static final By TEXT_FILTER = By.xpath("//android.widget.TextView[@text='Filter']");
	public static final By IMG_AVATAR = By.id("com.happydev.wordoffice:id/tv_random_text");
	public static final By BTN_CONFIRM = By.id("com.happydev.wordoffice:id/tv_confirm");
	public static final By TITLE_MY_CLOUD = By.id("com.happydev.wordoffice:id/textTilte");
	public static final By TEXT_WELL_COME_TO_CLOUD = By.xpath("//android.widget.TextView[@text='Welcome to Cloud']");
	public static final By BTN_LOGIN_WITH_GOOGLE_DRIVER = By.id("com.happydev.wordoffice:id/tv_gg_drive_login");
	public static final By BTN_LOGIN_WITH_ONE_DRIVER = By.id("com.happydev.wordoffice:id/tv_onedrive_login");
	public static final By BTN_TITLE_BACK = By.id("com.happydev.wordoffice:id/btnTitleBack");
	public static final By TEXT_WELCOME = By.id("com.happydev.wordoffice:id/tv_welcome");
	public static final By TEXT_LOGIN_TO_GOOGLE_DRIVER = By.id("com.happydev.wordoffice:id/tv_to_login");
	public static final By BTN_LOGIN = By.id("com.happydev.wordoffice:id/iv_to_login");
	public static final By TAB_LEARN_ABOUT_PREMIUM_FEATURES = By.id("com.happydev.wordoffice:id/ln_premium");
	public static final By BTN_START_FREE_TRIAL = By.id("com.happydev.wordoffice:id/ln_premium_sub");
	public static final By BTN_IV_CLOSE_PREMIUM = By.id("com.happydev.wordoffice:id/iv_close_premium");
	public static final By BTN_REMOVE_ADS = By.id("com.happydev.wordoffice:id/ln_remove_ads");
	public static final By TEXT_ARE_YOU_SURE = By.xpath("//android.widget.TextView[@text='Are you annoyed with advertising?']");
	public static final By BTN_REMOVE_ADS_NOW = By.id("com.happydev.wordoffice:id/ln_remove_ads_now");
	public static final By BTN_IV_CLOSE = By.id("com.happydev.wordoffice:id/iv_close");	
	public static final By BTN_PREMIUM = By.id("com.happydev.wordoffice:id/ln_premium_slide");
	public static final By BTN_MY_CLOUD = By.id("com.happydev.wordoffice:id/ln_cloud_slide");
	public static final By BTN_SETTING = By.id("com.happydev.wordoffice:id/ln_setting_slide");
	public static final By BTN_POLICY = By.id("com.happydev.wordoffice:id/ln_policy");
	public static final By BTN_TEAM_AND_CONDITION = By.id("com.happydev.wordoffice:id/ln_term_of_use");
	public static final By BTN_RATE = By.id("com.happydev.wordoffice:id/ln_rate");
	public static final By BTN_FEEDBACK = By.id("com.happydev.wordoffice:id/ln_feedback");
	public static final By BTN_VERSION_UPDATE = By.id("com.happydev.wordoffice:id/ln_version");
	public static final By BTN_LANGUAGE = By.id("com.happydev.wordoffice:id/ln_language");
	public static final By BTN_FACEBOOK = By.id("com.happydev.wordoffice:id/ln_facebook");
	public static final By TEXT_PRIVILLEGE = By.xpath("//android.widget.TextView[@text='Privilege']");
	public static final By TEXT_NORMAL = By.xpath("//android.widget.TextView[@text='Normal']");
	public static final By TEXT_PREMIUM = By.xpath("//android.widget.TextView[@text='Premium']");
	public static final By BANNER_PACKAGE2 = By.id("com.happydev.wordoffice:id/secondPack_title");
	public static final By TEXT_DAY = By.id("com.happydev.wordoffice:id/secondPack_des");
	public static final By TEXT_START_FREE_TRIAL = By.xpath("//android.widget.TextView[@text='Start Free Trial']");
	public static final By BANNER_PACKAGE1 = By.id("com.happydev.wordoffice:id/ln_first_pack");
	public static final By TEXT_MONTHLY = By.id("com.happydev.wordoffice:id/firstPack_title");
	public static final By BNT_UPGRADE_TO_PREMIUM = By.xpath("//android.widget.TextView[@text='Upgrade to Premium']");
	public static final By BANNER_PACKAGE3 = By.id("com.happydev.wordoffice:id/ln_third_pack");
	public static final By TEXT_LIFETIME = By.id("com.happydev.wordoffice:id/thirdPack_title");
	public static final By TEXT_SUBSCRIPTION_TERMS = By.xpath("//android.widget.TextView[@text='Subscription Terms']");
	public static final By TEXT_TERM_AND_CONDITION = By.id("com.happydev.wordoffice:id/tv_term");
	public static final By TEXT_PRIVACY_POLICY = By.id("com.happydev.wordoffice:id/tv_policy");
	public static final By TEXT_BASIC_READING_OPERATION = By.xpath("//android.widget.TextView[@text='Basic Reading Operation']");
	public static final By TEXT_AD_FREE = By.xpath("//android.widget.TextView[contains(@text,'Ad-Free')]");
	public static final By TEXT_CREATE_ALL_FIRE = By.xpath("//android.widget.TextView[@text='Create All Files']");
	public static final By TEXT_CONVERT_TO_PDF = By.xpath("//android.widget.TextView[@text='Convert to PDF']");
	public static final By TEXT_POWERFUL_EDITING_TOOL = By.xpath("//android.widget.TextView[@text='Powerful Editing Tool']");
	public static final By TEXT_VIEW_AS = By.xpath("//android.widget.TextView[@text='View As']");
	public static final By TEXT_SORT_BY = By.xpath("//android.widget.TextView[@text='Sort by']");
	public static final By TEXT_ORDER = By.xpath("//android.widget.TextView[@text='Order']");
	public static final By LIST_VIEW = By.xpath("//android.widget.TextView[@text='List View']");
	public static final By RAD_SORT_BY_NAME = By.id("com.happydev.wordoffice:id/rb_sort_name");
	public static final By RAD_SORT_BY_SIZE = By.id("com.happydev.wordoffice:id/rb_order_desc");
	public static final By RAD_ASCENDING = By.id("com.happydev.wordoffice:id/rb_order_asc");
	public static final By BTN_APPLY = By.id("com.happydev.wordoffice:id/tv_sort_apply");
	public static final By RAD_SORT_BY_DATE = By.id("com.happydev.wordoffice:id/rb_sort_date");
	public static final By RAD_SORT_BY_TYPE = By.id("com.happydev.wordoffice:id/rb_sort_type");
	public static final By RAD_DESCENDING = By.id("com.happydev.wordoffice:id/rb_order_desc");
	public static final By TEXT_GRID_VIEW = By.xpath("//android.widget.TextView[@text='Grid View']");
	public static final By TAB_RECENT = By.xpath("//android.widget.HorizontalScrollView[@resource-id='com.happydev.wordoffice:id/tab_recent']//android.widget.TextView[@text='Recent']");
	public static final By TEXT_FILE_NAME_GRID_VIEW = By.id("com.happydev.wordoffice:id/tv_grid_doc_name");
	public static final By TAB_FAVOURITE_IN_RECENT = By.xpath("//android.widget.TextView[@text='Favourite']");
	public static final By TEXT_BLANK = By.id("com.happydev.wordoffice:id/txt_addBlank");
	public static final By LIST_NAME_AVAILABLE_FORM = By.xpath("//android.widget.TextView[@resource-id='com.happydev.wordoffice:id/tv_template_name']");
	public static final By BTN_INTERAL_STORAGE = By.xpath("//android.widget.TextView[@resource-id='com.happydev.wordoffice:id/tv_name' and @text='Internal Storage']");
	public static final By BTN_SD_CARD = By.xpath("//android.widget.TextView[@resource-id='com.happydev.wordoffice:id/tv_name' and @text='SD card']");
	public static final By BTN_DEVICES_FILE = By.xpath("//android.widget.TextView[@resource-id='com.happydev.wordoffice:id/tv_name' and @text='Device Files']");
	public static final By BTN_ADD_ACCOUNT = By.xpath("//android.widget.TextView[@resource-id='com.happydev.wordoffice:id/tv_name' and @text='Add Account']");
	public static final By FOLDER_MOVIES = By.xpath("//android.widget.TextView[contains(@text,'Movies')]");
	public static final By FOLDER_MUSIC = By.xpath("//android.widget.TextView[contains(@text,'Music')]");
	public static final By TITLE_RECENT = By.xpath("//android.widget.TextView[@text='Recent']");
	public static final By LIST_FILE_IN_FOLDER = By.xpath("//android.widget.LinearLayout[@resource-id='com.google.android.documentsui:id/item_root']");
	public static final By TEXT_ALL_IMAGE = By.id("com.happydev.wordoffice:id/tvGalleryName");
	public static final By TEXT_WIFI_CONNECTED = By.id("com.happydev.wordoffice:id/cb_network_state");
	public static final By BTN_TURN_ON = By.id("com.happydev.wordoffice:id/tv_turn");
	public static final By LIST_FOLDER = By.xpath("//android.widget.TextView[@resource-id='com.happydev.wordoffice:id/tv_name']");
	public static final String OPTION_LANGUAGE = "//android.widget.TextView[@resource-id=\"com.happydev.wordoffice:id/itFirstLanguage_tvName\" and @text=\"&option\"]";
	
	
}
